### ISSUE TITLE
ng-repeat not showing elements

### ISSUE THREAD

**Issue by trevans24** [den-materials/rapid-prototype#1]
http://stackoverflow.com/questions/28880702/ng-repeat-not-showing-any-value
http://stackoverflow.com/questions/42136359/ng-repeat-not-showing-elements-of-array
http://stackoverflow.com/questions/24556179/angular-js-ng-repeat-not-showing-up

Alexi cant see what was going wrong with it

they are showing up as elements in Dev tools but not rendering on the page

**Comment by ZebGirouard** [comment]
Off to a great start, closing...
