### ISSUE TITLE
put request to upvote comments returning with unhelpful 500

### ISSUE THREAD

**Issue by JacyAnderson** [den-materials/rapid-prototype#4]
^ title.

http://stackoverflow.com/questions/36029616/angularjs-500-internal-server-error-for-http-put
http://stackoverflow.com/questions/32685120/update-and-put-routes-responding-error-500
 Asked Taylor and BIll to no avail.

**Comment by ZebGirouard** [comment]
Not sure what's going on, but at least it's working now :)
